services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXTERNAL_API_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - dbdata:/app/${DB_DIR}

volumes:
  dbdata:
